In [45]:
%pip install requests pandas python-dotenv

Requirement already satisfied: requests in .\anaconda3\Lib\site-packages (2.33.1)
Requirement already satisfied: pandas in .\anaconda3\Lib\site-packages (3.0.2)
Requirement already satisfied: python-dotenv in .\anaconda3\Lib\site-packages (0.21.0)
Requirement already satisfied: charset_normalizer<4,>=2 in .\anaconda3\Lib\site-packages (from requests) (2.0.4)
Requirement already satisfied: idna<4,>=2.5 in .\anaconda3\Lib\site-packages (from requests) (3.4)
Requirement already satisfied: urllib3<3,>=1.26 in .\anaconda3\Lib\site-packages (from requests) (2.0.7)
Requirement already satisfied: certifi>=2023.5.7 in .\anaconda3\Lib\site-packages (from requests) (2026.1.4)
Requirement already satisfied: numpy>=1.26.0 in .\anaconda3\Lib\site-packages (from pandas) (1.26.4)
Requirement already satisfied: python-dateutil>=2.8.2 in .\anaconda3\Lib\site-packages (from pandas) (2.8.2)
Requirement already satisfied: tzdata in .\anaconda3\Lib\site-packages (from pandas) (2023.3)
Requirement already satisfied: six>=1.5 in .\anaconda3\Lib\site-packages (from python-dateutil>=2.8.2->pandas) (1.16.0)
Note: you may need to restart the kernel to use updated packages.

In [47]:
import os
import io
import base64
from pathlib import Path

import requests
import pandas as pd
from dotenv import load_dotenv

In [49]:
PROJECT_ROOT = Path(r"C:\Users\swapn\OneDrive\Desktop\fuel_poverty_risk_england")
RAW_PATH = PROJECT_ROOT / "data" / "raw"
RAW_PATH.mkdir(parents=True, exist_ok=True)

load_dotenv(PROJECT_ROOT / ".env")

EPC_EMAIL = os.getenv("EPC_EMAIL")
EPC_API_KEY = os.getenv("EPC_API_KEY")

LA_CODE = "E06000047"   # County Durham
BASE_URL = "https://epc.opendatacommunities.org/api/v1/domestic/search"

assert EPC_EMAIL, "EPC_EMAIL missing in .env"
assert EPC_API_KEY, "EPC_API_KEY missing in .env"

print("Paths and environment loaded successfully")

Paths and environment loaded successfully

In [51]:
credentials = f"{EPC_EMAIL}:{EPC_API_KEY}"
token = base64.b64encode(credentials.encode("utf-8")).decode("utf-8")

HEADERS = {
    "Accept": "text/csv",
    "Authorization": f"Basic {token}"
}

print("Authorization header prepared")

Authorization header prepared

In [53]:
params = {
    "local-authority": LA_CODE,
    "size": 200
}

resp = requests.get(BASE_URL, headers=HEADERS, params=params, timeout=60)

print("Status code:", resp.status_code)
print("Content-Type:", resp.headers.get("Content-Type"))
print("X-Next-Search-After:", resp.headers.get("X-Next-Search-After"))

if resp.status_code != 200:
    print(resp.text[:500])
else:
    epc_test = pd.read_csv(io.StringIO(resp.text))
    print("Shape:", epc_test.shape)
    display(epc_test.head())

Status code: 200
Content-Type: text/csv; charset=utf-8
X-Next-Search-After: 2026-02-25:1aeee36a0aef5eeef9907d9321aeea686f74e04016bef36a35983dc96b200b2e
Shape: (200, 93)

,lmk-key,address1,address2,address3,postcode,building-reference-number,current-energy-rating,potential-energy-rating,current-energy-efficiency,potential-energy-efficiency,property-type,built-form,inspection-date,local-authority,constituency,county,lodgement-date,transaction-type,environment-impact-current,environment-impact-potential,energy-consumption-current,energy-consumption-potential,co2-emissions-current,co2-emiss-curr-per-floor-area,co2-emissions-potential,lighting-cost-current,lighting-cost-potential,heating-cost-current,heating-cost-potential,hot-water-cost-current,hot-water-cost-potential,total-floor-area,energy-tariff,mains-gas-flag,floor-level,flat-top-storey,flat-storey-count,main-heating-controls,multi-glaze-proportion,glazed-type,glazed-area,extension-count,number-habitable-rooms,number-heated-rooms,low-energy-lighting,number-open-fireplaces,hotwater-description,hot-water-energy-eff,hot-water-env-eff,floor-description,floor-energy-eff,floor-env-eff,windows-description,windows-energy-eff,windows-env-eff,walls-description,walls-energy-eff,walls-env-eff,secondheat-description,sheating-energy-eff,sheating-env-eff,roof-description,roof-energy-eff,roof-env-eff,mainheat-description,mainheat-energy-eff,mainheat-env-eff,mainheatcont-description,mainheatc-energy-eff,mainheatc-env-eff,lighting-description,lighting-energy-eff,lighting-env-eff,main-fuel,wind-turbine-count,heat-loss-corridor,unheated-corridor-length,floor-height,photo-supply,solar-water-heating-flag,mechanical-ventilation,address,local-authority-label,constituency-label,posttown,construction-age-band,lodgement-datetime,tenure,fixed-lighting-outlets-count,low-energy-fixed-light-count,uprn,uprn-source,report-type
0,04c5833d6adc0d81622f23292531f8c35124fcbbcd9787...,16 Browney Lane,Browney,NaN,DH7 8HT,10008735802,C,B,74,84,House,Mid-Terrace,2026-02-27,E06000047,E14001173,NaN,2026-02-28,marketed sale,73,82,161,103,3.6,29,2.4,122,89,1060,724,186,186,123.0,Single,Y,NaN,NaN,NaN,NaN,100,NaN,NaN,0.0,4.0,4.0,71,NaN,From main system,Good,Good,"Suspended, no insulation (assumed)",NaN,NaN,Fully double glazed,Poor,Poor,"Solid brick, as built, no insulation (assumed)",Very Poor,Very Poor,NaN,NaN,NaN,"Pitched, 300 mm loft insulation",Very Good,Very Good,"Boiler and radiators, mains gas",Good,Good,"Programmer, room thermostat and TRVs",Good,Good,Below average lighting efficiency,Poor,Poor,mains gas (not community),0,NaN,NaN,2.30,0.0,N,NaN,"16 Browney Lane, Browney",County Durham,NaN,DURHAM,England and Wales: 1900-1929,2026-02-28 11:22:13,Owner-occupied,7,NaN,1.001104e+11,Energy Assessor,100
1,0d0cdd99b2700a31cda048522b47b54f53b6f9637583a7...,2 St. Bede Crescent,Thornley,NaN,DH6 3HN,10008746626,C,C,69,76,House,Semi-Detached,2026-02-25,E06000047,E14001211,NaN,2026-02-28,marketed sale,69,73,244,207,2.3,45,2.0,37,37,668,612,158,158,51.0,Single,Y,NaN,NaN,NaN,NaN,100,NaN,NaN,0.0,5.0,5.0,100,NaN,From main system,Good,Good,"Suspended, no insulation (assumed)",NaN,NaN,Fully double glazed,Average,Average,"Cavity wall, filled cavity",Good,Good,NaN,NaN,NaN,"Pitched, 400+ mm loft insulation",Very Good,Very Good,"Boiler and radiators, mains gas",Good,Good,"Programmer, room thermostat and TRVs",Good,Good,Good lighting efficiency,Good,Good,mains gas (not community),0,NaN,NaN,2.33,0.0,N,NaN,"2 St. Bede Crescent, Thornley",County Durham,NaN,DURHAM,England and Wales: 1930-1949,2026-02-28 11:30:44,Owner-occupied,8,NaN,1.001104e+11,Energy Assessor,100
2,1145f8aa7471f56bf7ad5e04804b91408d8d5695d7ba3f...,14 Wharnley Way,NaN,NaN,DH8 9QN,10008732179,C,C,69,77,House,End-Terrace,2026-02-28,E06000047,E14001389,NaN,2026-02-28,non marketed sale,65,71,211,171,5.3,39,4.4,75,75,1537,1293,215,215,136.0,Single,Y,NaN,NaN,NaN,NaN,100,NaN,NaN,3.0,6.0,6.0,100,1.0,From main system,Good,Good,"Suspended, no insulation (assumed)",NaN,NaN,Fully double glazed,Poor,Poor,"Cavity wall, filled cavity",Good,Good,NaN,NaN,NaN,"Pitched, 300 mm loft insulation",Very Good,Very Good,"Boiler and radiators, mains gas",Good,Good,"Programmer, room thermostat and TRVs",Good,Good,Excellent lighting efficiency,Very Good,Very Good,mains gas (not community),0,NaN,NaN,2.40,0.0,N,NaN,14 Wharnley Way,County Durham,NaN,CONSETT,England and Wales: 1967-1975,2026-02-28 16:19:59,Owner-occupied,43,NaN,1.001104e+11,Energy Assessor,100
3,1487888962c17873f24391641ecffdc790eefc2b658b21...,74 High Street,West Cornforth,NaN,DL17 9HS,10008804457,C,C,70,76,House,Detached,2026-02-27,E06000047,E14001382,NaN,2026-02-28,marketed sale,67,72,184,154,6.2,33,5.3,105,105,1909,1654,322,322,187.0,Single,Y,NaN,NaN,NaN,NaN,100,NaN,NaN,1.0,7.0,7.0,100,NaN,From main system,Good,Good,"Suspended, no insulation (assumed)",NaN,NaN,Fully double glazed,Average,Average,"Cavity wall, filled cavity",Good,Good,NaN,NaN,NaN,"Pitched, 250 mm loft insulation",Good,Good,"Boiler and radiators, mains gas",Good,Good,"Programmer, room thermostat and TRVs",Good,Good,Good lighting efficiency,Good,Good,mains gas (not community),0,NaN,NaN,2.40,0.0,N,NaN,"74 High Street, West Cornforth",County Durham,NaN,FERRYHILL,England and Wales: 1950-1966,2026-02-28 12:00:47,Owner-occupied,12,NaN,1.001105e+11,Energy Assessor,100
4,19dac0ac53e25416439598afd79cbf9ea623c2fed607a1...,9 Escomb Road,NaN,NaN,DL14 6AB,10008811726,C,B,69,83,House,Mid-Terrace,2026-02-28,E06000047,E14001101,NaN,2026-02-28,marketed sale,66,81,224,122,3.7,41,2.1,65,65,1080,608,206,207,90.0,Single,Y,NaN,NaN,NaN,NaN,100,NaN,NaN,1.0,5.0,5.0,100,NaN,From main system,Good,Good,"Solid, no insulation (assumed)",NaN,NaN,Fully double glazed,Average,Average,"Sandstone, as built, no insulation (assumed)",Very Poor,Very Poor,NaN,NaN,NaN,"Pitched, 300 mm loft insulation",Very Good,Very Good,"Boiler and radiators, mains gas",Good,Good,"Programmer, room thermostat and TRVs",Good,Good,Good lighting efficiency,Good,Good,mains gas (not community),0,NaN,NaN,2.30,0.0,N,NaN,9 Escomb Road,County Durham,NaN,BISHOP AUCKLAND,England and Wales: 1900-1929,2026-02-28 19:40:19,Owner-occupied,11,NaN,1.001105e+11,Energy Assessor,100

In [55]:
def fetch_epc_local_authority(local_authority_code, page_size=5000, max_pages=None):
    if page_size > 5000:
        raise ValueError("page_size cannot exceed 5000")

    frames = []
    search_after = None
    page = 1

    while True:
        params = {
            "local-authority": local_authority_code,
            "size": page_size
        }

        if search_after:
            params["search-after"] = search_after

        resp = requests.get(BASE_URL, headers=HEADERS, params=params, timeout=120)

        if resp.status_code != 200:
            raise RuntimeError(
                f"Request failed on page {page}: {resp.status_code}\n{resp.text[:500]}"
            )

        df = pd.read_csv(io.StringIO(resp.text))
        print(f"Page {page}: {df.shape[0]} rows")

        if not df.empty:
            frames.append(df)

        search_after = resp.headers.get("X-Next-Search-After")

        if not search_after:
            break

        if max_pages is not None and page >= max_pages:
            break

        page += 1

    if not frames:
        return pd.DataFrame()

    out = pd.concat(frames, ignore_index=True)

    if "lmk-key" in out.columns:
        out = out.drop_duplicates(subset=["lmk-key"], keep="first")

    return out

In [57]:
epc_sample = fetch_epc_local_authority(LA_CODE, page_size=200, max_pages=1)

print("Final shape:", epc_sample.shape)
display(epc_sample.head())

Page 1: 200 rows
Final shape: (200, 93)

,lmk-key,address1,address2,address3,postcode,building-reference-number,current-energy-rating,potential-energy-rating,current-energy-efficiency,potential-energy-efficiency,property-type,built-form,inspection-date,local-authority,constituency,county,lodgement-date,transaction-type,environment-impact-current,environment-impact-potential,energy-consumption-current,energy-consumption-potential,co2-emissions-current,co2-emiss-curr-per-floor-area,co2-emissions-potential,lighting-cost-current,lighting-cost-potential,heating-cost-current,heating-cost-potential,hot-water-cost-current,hot-water-cost-potential,total-floor-area,energy-tariff,mains-gas-flag,floor-level,flat-top-storey,flat-storey-count,main-heating-controls,multi-glaze-proportion,glazed-type,glazed-area,extension-count,number-habitable-rooms,number-heated-rooms,low-energy-lighting,number-open-fireplaces,hotwater-description,hot-water-energy-eff,hot-water-env-eff,floor-description,floor-energy-eff,floor-env-eff,windows-description,windows-energy-eff,windows-env-eff,walls-description,walls-energy-eff,walls-env-eff,secondheat-description,sheating-energy-eff,sheating-env-eff,roof-description,roof-energy-eff,roof-env-eff,mainheat-description,mainheat-energy-eff,mainheat-env-eff,mainheatcont-description,mainheatc-energy-eff,mainheatc-env-eff,lighting-description,lighting-energy-eff,lighting-env-eff,main-fuel,wind-turbine-count,heat-loss-corridor,unheated-corridor-length,floor-height,photo-supply,solar-water-heating-flag,mechanical-ventilation,address,local-authority-label,constituency-label,posttown,construction-age-band,lodgement-datetime,tenure,fixed-lighting-outlets-count,low-energy-fixed-light-count,uprn,uprn-source,report-type
0,04c5833d6adc0d81622f23292531f8c35124fcbbcd9787...,16 Browney Lane,Browney,NaN,DH7 8HT,10008735802,C,B,74,84,House,Mid-Terrace,2026-02-27,E06000047,E14001173,NaN,2026-02-28,marketed sale,73,82,161,103,3.6,29,2.4,122,89,1060,724,186,186,123.0,Single,Y,NaN,NaN,NaN,NaN,100,NaN,NaN,0.0,4.0,4.0,71,NaN,From main system,Good,Good,"Suspended, no insulation (assumed)",NaN,NaN,Fully double glazed,Poor,Poor,"Solid brick, as built, no insulation (assumed)",Very Poor,Very Poor,NaN,NaN,NaN,"Pitched, 300 mm loft insulation",Very Good,Very Good,"Boiler and radiators, mains gas",Good,Good,"Programmer, room thermostat and TRVs",Good,Good,Below average lighting efficiency,Poor,Poor,mains gas (not community),0,NaN,NaN,2.30,0.0,N,NaN,"16 Browney Lane, Browney",County Durham,NaN,DURHAM,England and Wales: 1900-1929,2026-02-28 11:22:13,Owner-occupied,7,NaN,1.001104e+11,Energy Assessor,100
1,0d0cdd99b2700a31cda048522b47b54f53b6f9637583a7...,2 St. Bede Crescent,Thornley,NaN,DH6 3HN,10008746626,C,C,69,76,House,Semi-Detached,2026-02-25,E06000047,E14001211,NaN,2026-02-28,marketed sale,69,73,244,207,2.3,45,2.0,37,37,668,612,158,158,51.0,Single,Y,NaN,NaN,NaN,NaN,100,NaN,NaN,0.0,5.0,5.0,100,NaN,From main system,Good,Good,"Suspended, no insulation (assumed)",NaN,NaN,Fully double glazed,Average,Average,"Cavity wall, filled cavity",Good,Good,NaN,NaN,NaN,"Pitched, 400+ mm loft insulation",Very Good,Very Good,"Boiler and radiators, mains gas",Good,Good,"Programmer, room thermostat and TRVs",Good,Good,Good lighting efficiency,Good,Good,mains gas (not community),0,NaN,NaN,2.33,0.0,N,NaN,"2 St. Bede Crescent, Thornley",County Durham,NaN,DURHAM,England and Wales: 1930-1949,2026-02-28 11:30:44,Owner-occupied,8,NaN,1.001104e+11,Energy Assessor,100
2,1145f8aa7471f56bf7ad5e04804b91408d8d5695d7ba3f...,14 Wharnley Way,NaN,NaN,DH8 9QN,10008732179,C,C,69,77,House,End-Terrace,2026-02-28,E06000047,E14001389,NaN,2026-02-28,non marketed sale,65,71,211,171,5.3,39,4.4,75,75,1537,1293,215,215,136.0,Single,Y,NaN,NaN,NaN,NaN,100,NaN,NaN,3.0,6.0,6.0,100,1.0,From main system,Good,Good,"Suspended, no insulation (assumed)",NaN,NaN,Fully double glazed,Poor,Poor,"Cavity wall, filled cavity",Good,Good,NaN,NaN,NaN,"Pitched, 300 mm loft insulation",Very Good,Very Good,"Boiler and radiators, mains gas",Good,Good,"Programmer, room thermostat and TRVs",Good,Good,Excellent lighting efficiency,Very Good,Very Good,mains gas (not community),0,NaN,NaN,2.40,0.0,N,NaN,14 Wharnley Way,County Durham,NaN,CONSETT,England and Wales: 1967-1975,2026-02-28 16:19:59,Owner-occupied,43,NaN,1.001104e+11,Energy Assessor,100
3,1487888962c17873f24391641ecffdc790eefc2b658b21...,74 High Street,West Cornforth,NaN,DL17 9HS,10008804457,C,C,70,76,House,Detached,2026-02-27,E06000047,E14001382,NaN,2026-02-28,marketed sale,67,72,184,154,6.2,33,5.3,105,105,1909,1654,322,322,187.0,Single,Y,NaN,NaN,NaN,NaN,100,NaN,NaN,1.0,7.0,7.0,100,NaN,From main system,Good,Good,"Suspended, no insulation (assumed)",NaN,NaN,Fully double glazed,Average,Average,"Cavity wall, filled cavity",Good,Good,NaN,NaN,NaN,"Pitched, 250 mm loft insulation",Good,Good,"Boiler and radiators, mains gas",Good,Good,"Programmer, room thermostat and TRVs",Good,Good,Good lighting efficiency,Good,Good,mains gas (not community),0,NaN,NaN,2.40,0.0,N,NaN,"74 High Street, West Cornforth",County Durham,NaN,FERRYHILL,England and Wales: 1950-1966,2026-02-28 12:00:47,Owner-occupied,12,NaN,1.001105e+11,Energy Assessor,100
4,19dac0ac53e25416439598afd79cbf9ea623c2fed607a1...,9 Escomb Road,NaN,NaN,DL14 6AB,10008811726,C,B,69,83,House,Mid-Terrace,2026-02-28,E06000047,E14001101,NaN,2026-02-28,marketed sale,66,81,224,122,3.7,41,2.1,65,65,1080,608,206,207,90.0,Single,Y,NaN,NaN,NaN,NaN,100,NaN,NaN,1.0,5.0,5.0,100,NaN,From main system,Good,Good,"Solid, no insulation (assumed)",NaN,NaN,Fully double glazed,Average,Average,"Sandstone, as built, no insulation (assumed)",Very Poor,Very Poor,NaN,NaN,NaN,"Pitched, 300 mm loft insulation",Very Good,Very Good,"Boiler and radiators, mains gas",Good,Good,"Programmer, room thermostat and TRVs",Good,Good,Good lighting efficiency,Good,Good,mains gas (not community),0,NaN,NaN,2.30,0.0,N,NaN,9 Escomb Road,County Durham,NaN,BISHOP AUCKLAND,England and Wales: 1900-1929,2026-02-28 19:40:19,Owner-occupied,11,NaN,1.001105e+11,Energy Assessor,100

In [59]:
sample_file = RAW_PATH / f"epc_sample_{LA_CODE}.csv"
epc_sample.to_csv(sample_file, index=False)

print("Saved sample to:", sample_file)

Saved sample to: C:\Users\swapn\OneDrive\Desktop\fuel_poverty_risk_england\data\raw\epc_sample_E06000047.csv

In [61]:
key_cols = [
    "lmk-key",
    "address1",
    "address2",
    "address3",
    "postcode",
    "building-reference-number",
    "current-energy-rating",
    "potential-energy-rating",
    "current-energy-efficiency",
    "potential-energy-efficiency",
    "property-type",
    "built-form",
    "inspection-date",
    "local-authority",
    "constituency",
    "county",
    "lodgement-date",
    "transaction-type",
    "environment-impact-current",
    "environment-impact-potential"
]

display(epc_sample[key_cols].head())
print(epc_sample.columns.tolist())

,lmk-key,address1,address2,address3,postcode,building-reference-number,current-energy-rating,potential-energy-rating,current-energy-efficiency,potential-energy-efficiency,property-type,built-form,inspection-date,local-authority,constituency,county,lodgement-date,transaction-type,environment-impact-current,environment-impact-potential
0,04c5833d6adc0d81622f23292531f8c35124fcbbcd9787...,16 Browney Lane,Browney,NaN,DH7 8HT,10008735802,C,B,74,84,House,Mid-Terrace,2026-02-27,E06000047,E14001173,NaN,2026-02-28,marketed sale,73,82
1,0d0cdd99b2700a31cda048522b47b54f53b6f9637583a7...,2 St. Bede Crescent,Thornley,NaN,DH6 3HN,10008746626,C,C,69,76,House,Semi-Detached,2026-02-25,E06000047,E14001211,NaN,2026-02-28,marketed sale,69,73
2,1145f8aa7471f56bf7ad5e04804b91408d8d5695d7ba3f...,14 Wharnley Way,NaN,NaN,DH8 9QN,10008732179,C,C,69,77,House,End-Terrace,2026-02-28,E06000047,E14001389,NaN,2026-02-28,non marketed sale,65,71
3,1487888962c17873f24391641ecffdc790eefc2b658b21...,74 High Street,West Cornforth,NaN,DL17 9HS,10008804457,C,C,70,76,House,Detached,2026-02-27,E06000047,E14001382,NaN,2026-02-28,marketed sale,67,72
4,19dac0ac53e25416439598afd79cbf9ea623c2fed607a1...,9 Escomb Road,NaN,NaN,DL14 6AB,10008811726,C,B,69,83,House,Mid-Terrace,2026-02-28,E06000047,E14001101,NaN,2026-02-28,marketed sale,66,81

['lmk-key', 'address1', 'address2', 'address3', 'postcode', 'building-reference-number', 'current-energy-rating', 'potential-energy-rating', 'current-energy-efficiency', 'potential-energy-efficiency', 'property-type', 'built-form', 'inspection-date', 'local-authority', 'constituency', 'county', 'lodgement-date', 'transaction-type', 'environment-impact-current', 'environment-impact-potential', 'energy-consumption-current', 'energy-consumption-potential', 'co2-emissions-current', 'co2-emiss-curr-per-floor-area', 'co2-emissions-potential', 'lighting-cost-current', 'lighting-cost-potential', 'heating-cost-current', 'heating-cost-potential', 'hot-water-cost-current', 'hot-water-cost-potential', 'total-floor-area', 'energy-tariff', 'mains-gas-flag', 'floor-level', 'flat-top-storey', 'flat-storey-count', 'main-heating-controls', 'multi-glaze-proportion', 'glazed-type', 'glazed-area', 'extension-count', 'number-habitable-rooms', 'number-heated-rooms', 'low-energy-lighting', 'number-open-fireplaces', 'hotwater-description', 'hot-water-energy-eff', 'hot-water-env-eff', 'floor-description', 'floor-energy-eff', 'floor-env-eff', 'windows-description', 'windows-energy-eff', 'windows-env-eff', 'walls-description', 'walls-energy-eff', 'walls-env-eff', 'secondheat-description', 'sheating-energy-eff', 'sheating-env-eff', 'roof-description', 'roof-energy-eff', 'roof-env-eff', 'mainheat-description', 'mainheat-energy-eff', 'mainheat-env-eff', 'mainheatcont-description', 'mainheatc-energy-eff', 'mainheatc-env-eff', 'lighting-description', 'lighting-energy-eff', 'lighting-env-eff', 'main-fuel', 'wind-turbine-count', 'heat-loss-corridor', 'unheated-corridor-length', 'floor-height', 'photo-supply', 'solar-water-heating-flag', 'mechanical-ventilation', 'address', 'local-authority-label', 'constituency-label', 'posttown', 'construction-age-band', 'lodgement-datetime', 'tenure', 'fixed-lighting-outlets-count', 'low-energy-fixed-light-count', 'uprn', 'uprn-source', 'report-type']

In [63]:
epc_full = fetch_epc_local_authority(LA_CODE, page_size=5000)

full_file = RAW_PATH / f"epc_full_{LA_CODE}.csv"
epc_full.to_csv(full_file, index=False)

print("Full shape:", epc_full.shape)
print("Saved full file to:", full_file)

Page 1: 5000 rows
Page 2: 5000 rows
Page 3: 5000 rows
Page 4: 5000 rows
Page 5: 5000 rows
Page 6: 5000 rows
Page 7: 5000 rows
Page 8: 5000 rows
Page 9: 5000 rows
Page 10: 5000 rows
Page 11: 5000 rows
Page 12: 5000 rows
Page 13: 5000 rows
Page 14: 5000 rows
Page 15: 5000 rows
Page 16: 5000 rows
Page 17: 5000 rows
Page 18: 5000 rows
Page 19: 5000 rows
Page 20: 5000 rows
Page 21: 5000 rows
Page 22: 5000 rows
Page 23: 5000 rows
Page 24: 5000 rows
Page 25: 5000 rows
Page 26: 5000 rows
Page 27: 5000 rows
Page 28: 5000 rows
Page 29: 5000 rows
Page 30: 5000 rows
Page 31: 5000 rows
Page 32: 5000 rows
Page 33: 5000 rows
Page 34: 5000 rows
Page 35: 5000 rows
Page 36: 5000 rows
Page 37: 5000 rows
Page 38: 5000 rows
Page 39: 5000 rows
Page 40: 5000 rows
Page 41: 5000 rows
Page 42: 5000 rows
Page 43: 5000 rows
Page 44: 5000 rows
Page 45: 5000 rows
Page 46: 5000 rows
Page 47: 5000 rows
Page 48: 5000 rows
Page 49: 5000 rows
Page 50: 5000 rows
Page 51: 5000 rows
Page 52: 5000 rows
Page 53: 5000 rows
Page 54: 5000 rows
Page 55: 5000 rows
Page 56: 5000 rows
Page 57: 5000 rows
Page 58: 5000 rows
Page 59: 5000 rows
Page 60: 4445 rows
Page 61: 0 rows
Full shape: (299445, 93)
Saved full file to: C:\Users\swapn\OneDrive\Desktop\fuel_poverty_risk_england\data\raw\epc_full_E06000047.csv

In [65]:
keep_cols = [
    "lmk-key", "postcode", "current-energy-rating", "potential-energy-rating",
    "current-energy-efficiency", "potential-energy-efficiency",
    "property-type", "built-form", "inspection-date",
    "local-authority", "county", "transaction-type"
]

epc_clean = epc_full[keep_cols].copy()
epc_clean.head()

,lmk-key,postcode,current-energy-rating,potential-energy-rating,current-energy-efficiency,potential-energy-efficiency,property-type,built-form,inspection-date,local-authority,county,transaction-type
0,04c5833d6adc0d81622f23292531f8c35124fcbbcd9787...,DH7 8HT,C,B,74,84,House,Mid-Terrace,2026-02-27,E06000047,NaN,marketed sale
1,0d0cdd99b2700a31cda048522b47b54f53b6f9637583a7...,DH6 3HN,C,C,69,76,House,Semi-Detached,2026-02-25,E06000047,NaN,marketed sale
2,1145f8aa7471f56bf7ad5e04804b91408d8d5695d7ba3f...,DH8 9QN,C,C,69,77,House,End-Terrace,2026-02-28,E06000047,NaN,non marketed sale
3,1487888962c17873f24391641ecffdc790eefc2b658b21...,DL17 9HS,C,C,70,76,House,Detached,2026-02-27,E06000047,NaN,marketed sale
4,19dac0ac53e25416439598afd79cbf9ea623c2fed607a1...,DL14 6AB,C,B,69,83,House,Mid-Terrace,2026-02-28,E06000047,NaN,marketed sale

In [67]:
clean_file = RAW_PATH / f"epc_clean_{LA_CODE}.csv"
epc_clean.to_csv(clean_file, index=False)
print("Saved clean file to:", clean_file)

Saved clean file to: C:\Users\swapn\OneDrive\Desktop\fuel_poverty_risk_england\data\raw\epc_clean_E06000047.csv

In [69]:
print(epc_clean.shape)
print(epc_clean.isna().sum())
print("Duplicate lmk-key:", epc_clean["lmk-key"].duplicated().sum())

(299445, 12)
lmk-key                             0
postcode                            0
current-energy-rating               0
potential-energy-rating             0
current-energy-efficiency           0
potential-energy-efficiency         0
property-type                       0
built-form                          0
inspection-date                     0
local-authority                     0
county                         299443
transaction-type                    0
dtype: int64
Duplicate lmk-key: 0

In [71]:
epc_clean = epc_clean.drop(columns=["county"])
epc_clean.shape

(299445, 11)

In [73]:
clean_file = RAW_PATH / f"epc_clean_{LA_CODE}.csv"
epc_clean.to_csv(clean_file, index=False)
print("Saved:", clean_file)

Saved: C:\Users\swapn\OneDrive\Desktop\fuel_poverty_risk_england\data\raw\epc_clean_E06000047.csv

In [75]:
for col in ["current-energy-rating", "potential-energy-rating", "property-type", "built-form", "transaction-type"]:
    print(f"\n--- {col} ---")
    print(epc_clean[col].value_counts(dropna=False).head(20))

--- current-energy-rating ---
current-energy-rating
D    120568
C    105850
E     33911
B     26719
F      8064
G      2635
A      1698
Name: count, dtype: int64

--- potential-energy-rating ---
potential-energy-rating
B    157733
C     97164
A     22847
D     17462
E      2969
F       954
G       316
Name: count, dtype: int64

--- property-type ---
property-type
House         226987
Bungalow       46431
Flat           24184
Maisonette      1781
Park home         62
Name: count, dtype: int64

--- built-form ---
built-form
Semi-Detached           105398
Mid-Terrace              94517
Detached                 49898
End-Terrace              44890
NO DATA!                  1580
Enclosed Mid-Terrace      1191
Enclosed End-Terrace      1179
Not Recorded               792
Name: count, dtype: int64

--- transaction-type ---
transaction-type
marketed sale                                                                         102714
rental (social)                                                                        58621
rental                                                                                 33466
new dwelling                                                                           24960
none of the above                                                                      20995
rental (private)                                                                       20967
ECO assessment                                                                         11022
assessment for green deal                                                               8028
not sale or rental                                                                      6659
non marketed sale                                                                       5957
FiT application                                                                         3685
Stock condition survey                                                                   880
RHI application                                                                          639
following green deal                                                                     469
Non-grant scheme (e.g. MEES)                                                             137
rental (private) - this is for backwards compatibility only and should not be used        89
Grant scheme (ECO, RHI, etc.)                                                             49
unknown                                                                                   48
rental (social) - this is for backwards compatibility only and should not be used         37
re-mortgaging                                                                             11
Name: count, dtype: int64

In [77]:
for col in ["current-energy-rating", "potential-energy-rating", "property-type", "built-form", "transaction-type"]:
    print(f"\n--- {col} ---")
    print(epc_clean[col].value_counts(dropna=False).head(20))

--- current-energy-rating ---
current-energy-rating
D    120568
C    105850
E     33911
B     26719
F      8064
G      2635
A      1698
Name: count, dtype: int64

--- potential-energy-rating ---
potential-energy-rating
B    157733
C     97164
A     22847
D     17462
E      2969
F       954
G       316
Name: count, dtype: int64

--- property-type ---
property-type
House         226987
Bungalow       46431
Flat           24184
Maisonette      1781
Park home         62
Name: count, dtype: int64

--- built-form ---
built-form
Semi-Detached           105398
Mid-Terrace              94517
Detached                 49898
End-Terrace              44890
NO DATA!                  1580
Enclosed Mid-Terrace      1191
Enclosed End-Terrace      1179
Not Recorded               792
Name: count, dtype: int64

--- transaction-type ---
transaction-type
marketed sale                                                                         102714
rental (social)                                                                        58621
rental                                                                                 33466
new dwelling                                                                           24960
none of the above                                                                      20995
rental (private)                                                                       20967
ECO assessment                                                                         11022
assessment for green deal                                                               8028
not sale or rental                                                                      6659
non marketed sale                                                                       5957
FiT application                                                                         3685
Stock condition survey                                                                   880
RHI application                                                                          639
following green deal                                                                     469
Non-grant scheme (e.g. MEES)                                                             137
rental (private) - this is for backwards compatibility only and should not be used        89
Grant scheme (ECO, RHI, etc.)                                                             49
unknown                                                                                   48
rental (social) - this is for backwards compatibility only and should not be used         37
re-mortgaging                                                                             11
Name: count, dtype: int64

In [79]:
for col in ["current-energy-rating", "potential-energy-rating", "property-type", "built-form", "transaction-type"]:
    print(f"\n--- {col} ---")
    print(epc_clean[col].value_counts(dropna=False).head(20))

--- current-energy-rating ---
current-energy-rating
D    120568
C    105850
E     33911
B     26719
F      8064
G      2635
A      1698
Name: count, dtype: int64

--- potential-energy-rating ---
potential-energy-rating
B    157733
C     97164
A     22847
D     17462
E      2969
F       954
G       316
Name: count, dtype: int64

--- property-type ---
property-type
House         226987
Bungalow       46431
Flat           24184
Maisonette      1781
Park home         62
Name: count, dtype: int64

--- built-form ---
built-form
Semi-Detached           105398
Mid-Terrace              94517
Detached                 49898
End-Terrace              44890
NO DATA!                  1580
Enclosed Mid-Terrace      1191
Enclosed End-Terrace      1179
Not Recorded               792
Name: count, dtype: int64

--- transaction-type ---
transaction-type
marketed sale                                                                         102714
rental (social)                                                                        58621
rental                                                                                 33466
new dwelling                                                                           24960
none of the above                                                                      20995
rental (private)                                                                       20967
ECO assessment                                                                         11022
assessment for green deal                                                               8028
not sale or rental                                                                      6659
non marketed sale                                                                       5957
FiT application                                                                         3685
Stock condition survey                                                                   880
RHI application                                                                          639
following green deal                                                                     469
Non-grant scheme (e.g. MEES)                                                             137
rental (private) - this is for backwards compatibility only and should not be used        89
Grant scheme (ECO, RHI, etc.)                                                             49
unknown                                                                                   48
rental (social) - this is for backwards compatibility only and should not be used         37
re-mortgaging                                                                             11
Name: count, dtype: int64

In [81]:
epc_clean["inspection-date"] = pd.to_datetime(epc_clean["inspection-date"], errors="coerce")
print("Min date:", epc_clean["inspection-date"].min())
print("Max date:", epc_clean["inspection-date"].max())

Min date: 2005-04-28 00:00:00
Max date: 2026-02-28 00:00:00

In [83]:
epc_clean["inspection_year"] = epc_clean["inspection-date"].dt.year
epc_clean["inspection_year"].value_counts().sort_index()

inspection_year
2005        1
2007       24
2008     6342
2009    25951
2010    13427
2011    13983
2012    12210
2013    21871
2014    47361
2015    16869
2016    13459
2017    10464
2018    11213
2019    11591
2020    10929
2021    13183
2022    17561
2023    17058
2024    16525
2025    16404
2026     3019
Name: count, dtype: int64

In [85]:
clean_file = RAW_PATH / f"epc_clean_{LA_CODE}.csv"
epc_clean.to_csv(clean_file, index=False)
print("Saved:", clean_file)

Saved: C:\Users\swapn\OneDrive\Desktop\fuel_poverty_risk_england\data\raw\epc_clean_E06000047.csv

In [87]:
keep_cols = [
    "lmk-key", "building-reference-number", "postcode",
    "current-energy-rating", "potential-energy-rating",
    "current-energy-efficiency", "potential-energy-efficiency",
    "property-type", "built-form", "inspection-date",
    "local-authority", "transaction-type"
]

epc_clean = epc_full[keep_cols].copy()
epc_clean["inspection-date"] = pd.to_datetime(epc_clean["inspection-date"], errors="coerce")
epc_clean["inspection_year"] = epc_clean["inspection-date"].dt.year
epc_clean.head()

,lmk-key,building-reference-number,postcode,current-energy-rating,potential-energy-rating,current-energy-efficiency,potential-energy-efficiency,property-type,built-form,inspection-date,local-authority,transaction-type,inspection_year
0,04c5833d6adc0d81622f23292531f8c35124fcbbcd9787...,10008735802,DH7 8HT,C,B,74,84,House,Mid-Terrace,2026-02-27,E06000047,marketed sale,2026
1,0d0cdd99b2700a31cda048522b47b54f53b6f9637583a7...,10008746626,DH6 3HN,C,C,69,76,House,Semi-Detached,2026-02-25,E06000047,marketed sale,2026
2,1145f8aa7471f56bf7ad5e04804b91408d8d5695d7ba3f...,10008732179,DH8 9QN,C,C,69,77,House,End-Terrace,2026-02-28,E06000047,non marketed sale,2026
3,1487888962c17873f24391641ecffdc790eefc2b658b21...,10008804457,DL17 9HS,C,C,70,76,House,Detached,2026-02-27,E06000047,marketed sale,2026
4,19dac0ac53e25416439598afd79cbf9ea623c2fed607a1...,10008811726,DL14 6AB,C,B,69,83,House,Mid-Terrace,2026-02-28,E06000047,marketed sale,2026

In [89]:
epc_latest = (
    epc_clean
    .sort_values(["building-reference-number", "inspection-date"])
    .drop_duplicates(subset=["building-reference-number"], keep="last")
    .copy()
)

print(epc_latest.shape)
epc_latest.head()

(233972, 13)

,lmk-key,building-reference-number,postcode,current-energy-rating,potential-energy-rating,current-energy-efficiency,potential-energy-efficiency,property-type,built-form,inspection-date,local-authority,transaction-type,inspection_year
89990,397902962020071112130501106000,1216,DH6 2UX,C,C,77,79,Flat,Mid-Terrace,2020-07-10,E06000047,rental (private),2020
181463,401709042014101515021622149055,1255,DL14 9SN,D,C,57,71,House,Semi-Detached,2014-10-15,E06000047,assessment for green deal,2014
123903,477405332017050421245560003000,1303,DL14 9SW,F,E,23,53,House,Detached,2017-05-03,E06000047,marketed sale,2017
278424,466800042009042613064135112066,1326,DL14 9SW,E,D,52,66,House,Detached,2009-04-26,E06000047,marketed sale,2009
162981,83930352014110217550190749030,2305,DH8 0SG,D,B,65,91,House,Mid-Terrace,2014-10-30,E06000047,marketed sale,2014

In [95]:
latest_file = RAW_PATH / f"epc_latest_{LA_CODE}.csv"
epc_latest.to_csv(latest_file, index=False)
print("Saved:", latest_file)

Saved: C:\Users\swapn\OneDrive\Desktop\fuel_poverty_risk_england\data\raw\epc_latest_E06000047.csv

In [98]:
print("Rows in epc_full:", epc_full.shape[0])
print("Rows in epc_latest:", epc_latest.shape[0])
print("Unique building-reference-number:", epc_latest["building-reference-number"].nunique())

Rows in epc_full: 299445
Rows in epc_latest: 233972
Unique building-reference-number: 233972

In [100]:
epc_latest["is_low_rating"] = epc_latest["current-energy-rating"].isin(["E", "F", "G"]).astype(int)
epc_latest["is_low_efficiency"] = (epc_latest["current-energy-efficiency"] < 55).astype(int)
epc_latest["improvement_gap"] = (
    epc_latest["potential-energy-efficiency"] - epc_latest["current-energy-efficiency"]
)

print(epc_latest[["is_low_rating", "is_low_efficiency", "improvement_gap"]].describe())
print(epc_latest["is_low_rating"].value_counts())
print(epc_latest["is_low_efficiency"].value_counts())

       is_low_rating  is_low_efficiency  improvement_gap
count  233972.000000      233972.000000    233972.000000
mean        0.123609           0.123609        15.533769
std         0.329135           0.329135        20.208678
min         0.000000           0.000000        -1.000000
25%         0.000000           0.000000         9.000000
50%         0.000000           0.000000        15.000000
75%         0.000000           0.000000        20.000000
max         1.000000           1.000000      8347.000000
is_low_rating
0    205051
1     28921
Name: count, dtype: int64
is_low_efficiency
0    205051
1     28921
Name: count, dtype: int64

In [102]:
weird_gap = epc_latest[
    (epc_latest["improvement_gap"] < 0) |
    (epc_latest["improvement_gap"] > 100)
].copy()

print(weird_gap.shape)
weird_gap[[
    "building-reference-number",
    "current-energy-rating",
    "potential-energy-rating",
    "current-energy-efficiency",
    "potential-energy-efficiency",
    "improvement_gap"
]].head(20)

(30, 16)

,building-reference-number,current-energy-rating,potential-energy-rating,current-energy-efficiency,potential-energy-efficiency,improvement_gap
102754,1555004678,G,A,1,111,110
280249,1935699568,C,C,74,73,-1
280237,2113799568,C,C,74,73,-1
156500,2393415768,G,A,1,112,111
280278,2552799568,C,C,74,73,-1
135493,2646301868,G,A,1,112,111
280258,2842799568,C,C,74,73,-1
111160,3545379578,G,A,1,105,104
280203,3582799568,C,C,74,73,-1
280248,4173799568,C,C,74,73,-1
90953,4919540778,G,A,1,102,101
280257,6333799568,C,C,74,73,-1
280252,6412799568,C,C,74,73,-1
280202,6664799568,C,C,74,73,-1
280256,6863799568,C,C,74,73,-1
130321,7072154478,G,A,7,121,114
149561,7456786378,G,A,1,102,101
280209,7744799568,C,C,74,73,-1
280230,7835799568,C,C,74,73,-1
280201,8021799568,C,C,74,73,-1

In [104]:
epc_latest["improvement_gap_clean"] = epc_latest["improvement_gap"].where(
    (epc_latest["improvement_gap"] >= 0) & (epc_latest["improvement_gap"] <= 100)
)

epc_latest["improvement_gap_clean"].describe()

count    233942.000000
mean         15.494665
std          10.548862
min           0.000000
25%           9.000000
50%          15.000000
75%          20.000000
max         100.000000
Name: improvement_gap_clean, dtype: float64

In [106]:
latest_file = RAW_PATH / f"epc_latest_engineered_{LA_CODE}.csv"
epc_latest.to_csv(latest_file, index=False)
print("Saved:", latest_file)

Saved: C:\Users\swapn\OneDrive\Desktop\fuel_poverty_risk_england\data\raw\epc_latest_engineered_E06000047.csv

In [108]:
postcode_risk = (
    epc_latest
    .groupby("postcode", dropna=False)
    .agg(
        properties=("building-reference-number", "count"),
        share_low_rating=("is_low_rating", "mean"),
        share_low_efficiency=("is_low_efficiency", "mean"),
        avg_current_efficiency=("current-energy-efficiency", "mean"),
        avg_potential_efficiency=("potential-energy-efficiency", "mean"),
        avg_improvement_gap=("improvement_gap_clean", "mean")
    )
    .reset_index()
)

postcode_risk.head()

,postcode,properties,share_low_rating,share_low_efficiency,avg_current_efficiency,avg_potential_efficiency,avg_improvement_gap
0,DH1 1AB,3,0.333333,0.333333,54.000000,76.666667,22.666667
1,DH1 1AD,11,0.272727,0.272727,58.272727,84.272727,26.000000
2,DH1 1AE,7,0.000000,0.000000,65.428571,76.857143,11.428571
3,DH1 1AF,35,0.114286,0.114286,64.600000,79.371429,14.771429
4,DH1 1AG,2,0.000000,0.000000,64.000000,83.500000,19.500000

In [110]:
postcode_file = RAW_PATH / f"postcode_risk_{LA_CODE}.csv"
postcode_risk.to_csv(postcode_file, index=False)
print("Saved:", postcode_file)

Saved: C:\Users\swapn\OneDrive\Desktop\fuel_poverty_risk_england\data\raw\postcode_risk_E06000047.csv

In [112]:
postcode_risk.sort_values(
    ["share_low_rating", "share_low_efficiency", "properties"],
    ascending=[False, False, False]
).head(20)

,postcode,properties,share_low_rating,share_low_efficiency,avg_current_efficiency,avg_potential_efficiency,avg_improvement_gap
10726,DL2 3BL,12,1.0,1.0,38.500000,69.916667,31.416667
2024,DH3 4PH,11,1.0,1.0,37.545455,72.181818,34.636364
7314,DL13 2AY,11,1.0,1.0,34.818182,76.181818,41.363636
7857,DL13 5HA,11,1.0,1.0,39.545455,85.545455,46.000000
9195,DL15 0QU,10,1.0,1.0,49.600000,58.100000,8.500000
8070,DL14 0LJ,9,1.0,1.0,33.444444,80.444444,47.000000
3142,DH6 5JP,8,1.0,1.0,27.375000,92.625000,65.250000
7210,DL13 1JU,8,1.0,1.0,29.750000,78.000000,48.250000
7942,DL13 5QW,8,1.0,1.0,41.875000,76.750000,34.875000
10851,DL2 3QL,8,1.0,1.0,18.125000,87.500000,63.000000
10852,DL2 3QN,8,1.0,1.0,23.750000,77.000000,53.250000
10863,DL2 3RL,8,1.0,1.0,44.875000,78.250000,33.375000
13781,TS21 3BT,8,1.0,1.0,45.875000,71.750000,25.875000
7116,DL12 9TN,7,1.0,1.0,38.142857,90.000000,51.857143
7153,DL13 1BJ,7,1.0,1.0,17.714286,78.000000,53.500000
7280,DL13 1RQ,7,1.0,1.0,26.428571,75.571429,49.142857
7522,DL13 3AF,7,1.0,1.0,45.714286,70.857143,25.142857
7882,DL13 5JR,7,1.0,1.0,47.142857,92.857143,45.714286
10768,DL2 3HE,7,1.0,1.0,36.714286,96.142857,59.428571
2031,DH3 4PU,6,1.0,1.0,36.833333,75.166667,38.333333

In [114]:
postcode_risk_filtered = postcode_risk[postcode_risk["properties"] >= 20].copy()

postcode_risk_filtered.sort_values(
    ["share_low_rating", "share_low_efficiency", "properties"],
    ascending=[False, False, False]
).head(20)

,postcode,properties,share_low_rating,share_low_efficiency,avg_current_efficiency,avg_potential_efficiency,avg_improvement_gap
869,DH1 5HG,45,0.955556,0.955556,37.755556,52.933333,15.177778
9278,DL15 8AT,40,0.800000,0.800000,42.700000,73.925000,31.225000
14137,TS27 4SL,29,0.793103,0.793103,46.689655,76.172414,29.482759
4227,DH7 9QR,22,0.772727,0.772727,43.000000,76.681818,33.681818
7800,DL13 5AA,22,0.772727,0.772727,39.136364,77.363636,38.227273
9277,DL15 8AS,22,0.772727,0.772727,46.500000,80.954545,34.454545
197,DH1 2AA,33,0.757576,0.757576,41.636364,58.606061,16.969697
4095,DH7 9DF,24,0.750000,0.750000,46.125000,72.458333,26.333333
7260,DL13 1QJ,33,0.727273,0.727273,43.787879,77.212121,33.424242
7895,DL13 5LR,25,0.720000,0.720000,41.920000,77.200000,35.280000
6637,DL12 0QG,28,0.714286,0.714286,45.892857,72.000000,26.107143
6536,DL12 0AH,21,0.714286,0.714286,47.238095,75.095238,27.857143
6651,DL12 0RJ,21,0.714286,0.714286,46.809524,81.476190,34.666667
10736,DL2 3DL,24,0.708333,0.708333,49.083333,75.541667,26.458333
7946,DL13 5RF,27,0.703704,0.703704,47.074074,76.407407,29.333333
6645,DL12 0QW,37,0.702703,0.702703,40.648649,78.243243,37.594595
4088,DH7 9BW,20,0.700000,0.700000,49.150000,76.100000,26.950000
6653,DL12 0RN,20,0.700000,0.700000,46.450000,79.400000,32.950000
4071,DH7 9AR,22,0.681818,0.681818,45.954545,72.818182,26.863636
6511,DL11 7DU,22,0.681818,0.681818,47.863636,81.363636,33.500000

In [116]:
postcode_risk_filtered["risk_score"] = (
    0.4 * postcode_risk_filtered["share_low_rating"] +
    0.4 * postcode_risk_filtered["share_low_efficiency"] +
    0.2 * (postcode_risk_filtered["avg_improvement_gap"] / postcode_risk_filtered["avg_improvement_gap"].max())
)

postcode_risk_filtered.sort_values("risk_score", ascending=False).head(20)

,postcode,properties,share_low_rating,share_low_efficiency,avg_current_efficiency,avg_potential_efficiency,avg_improvement_gap,risk_score
869,DH1 5HG,45,0.955556,0.955556,37.755556,52.933333,15.177778,0.815462
7800,DL13 5AA,22,0.772727,0.772727,39.136364,77.363636,38.227273,0.746677
9278,DL15 8AT,40,0.800000,0.800000,42.700000,73.925000,31.225000,0.744958
9277,DL15 8AS,22,0.772727,0.772727,46.500000,80.954545,34.454545,0.733995
14137,TS27 4SL,29,0.793103,0.793103,46.689655,76.172414,29.482759,0.733584
4227,DH7 9QR,22,0.772727,0.772727,43.000000,76.681818,33.681818,0.731398
7895,DL13 5LR,25,0.720000,0.720000,41.920000,77.200000,35.280000,0.694588
7260,DL13 1QJ,33,0.727273,0.727273,43.787879,77.212121,33.424242,0.694169
6645,DL12 0QW,37,0.702703,0.702703,40.648649,78.243243,37.594595,0.688531
4095,DH7 9DF,24,0.750000,0.750000,46.125000,72.458333,26.333333,0.688515
6651,DL12 0RJ,21,0.714286,0.714286,46.809524,81.476190,34.666667,0.687955
6653,DL12 0RN,20,0.700000,0.700000,46.450000,79.400000,32.950000,0.670756
6536,DL12 0AH,21,0.714286,0.714286,47.238095,75.095238,27.857143,0.665066
197,DH1 2AA,33,0.757576,0.757576,41.636364,58.606061,16.969697,0.663102
7946,DL13 5RF,27,0.703704,0.703704,47.074074,76.407407,29.333333,0.661562
6637,DL12 0QG,28,0.714286,0.714286,45.892857,72.000000,26.107143,0.659184
6511,DL11 7DU,22,0.681818,0.681818,47.863636,81.363636,33.500000,0.658060
10853,DL2 3QP,61,0.655738,0.655738,43.508197,83.049180,39.540984,0.657501
10736,DL2 3DL,24,0.708333,0.708333,49.083333,75.541667,26.458333,0.655602
8581,DL14 8AT,51,0.666667,0.666667,49.313725,85.588235,36.274510,0.655264

In [118]:
postcode_score_file = RAW_PATH / f"postcode_risk_scored_{LA_CODE}.csv"
postcode_risk_filtered.to_csv(postcode_score_file, index=False)
print("Saved:", postcode_score_file)

Saved: C:\Users\swapn\OneDrive\Desktop\fuel_poverty_risk_england\data\raw\postcode_risk_scored_E06000047.csv

In [120]:
postcode_risk_filtered["risk_band"] = pd.qcut(
    postcode_risk_filtered["risk_score"],
    q=5,
    labels=["Very Low", "Low", "Medium", "High", "Very High"]
)

postcode_risk_filtered[["postcode", "properties", "risk_score", "risk_band"]].sort_values(
    "risk_score", ascending=False
).head(20)

       postcode  properties  risk_score  risk_band
869     DH1 5HG          45    0.815462  Very High
7800   DL13 5AA          22    0.746677  Very High
9278   DL15 8AT          40    0.744958  Very High
9277   DL15 8AS          22    0.733995  Very High
14137  TS27 4SL          29    0.733584  Very High
4227    DH7 9QR          22    0.731398  Very High
7895   DL13 5LR          25    0.694588  Very High
7260   DL13 1QJ          33    0.694169  Very High
6645   DL12 0QW          37    0.688531  Very High
4095    DH7 9DF          24    0.688515  Very High
6651   DL12 0RJ          21    0.687955  Very High
6653   DL12 0RN          20    0.670756  Very High
6536   DL12 0AH          21    0.665066  Very High
197     DH1 2AA          33    0.663102  Very High
7946   DL13 5RF          27    0.661562  Very High
6637   DL12 0QG          28    0.659184  Very High
6511   DL11 7DU          22    0.658060  Very High
10853   DL2 3QP          61    0.657501  Very High
10736   DL2 3DL          24    0.655602  Very High
8581   DL14 8AT          51    0.655264  Very High

In [122]:
final_file = RAW_PATH / f"postcode_risk_final_{LA_CODE}.csv"
postcode_risk_filtered.to_csv(final_file, index=False)
print("Saved:", final_file)

Saved: C:\Users\swapn\OneDrive\Desktop\fuel_poverty_risk_england\data\raw\postcode_risk_final_E06000047.csv

In [124]:
postcode_risk_filtered["risk_band"].value_counts()

risk_band
Very Low     886
Low          886
High         886
Very High    886
Medium       885
Name: count, dtype: int64

In [126]:
summary = pd.DataFrame([{
    "local_authority": LA_CODE,
    "properties_total": epc_latest.shape[0],
    "postcodes_total": postcode_risk_filtered.shape[0],
    "low_rating_share": epc_latest["is_low_rating"].mean(),
    "low_efficiency_share": epc_latest["is_low_efficiency"].mean(),
    "avg_current_efficiency": epc_latest["current-energy-efficiency"].mean(),
    "avg_potential_efficiency": epc_latest["potential-energy-efficiency"].mean(),
    "avg_improvement_gap": epc_latest["improvement_gap_clean"].mean()
}])

summary

,local_authority,properties_total,postcodes_total,low_rating_share,low_efficiency_share,avg_current_efficiency,avg_potential_efficiency,avg_improvement_gap
0,E06000047,233972,4429,0.123609,0.123609,66.644915,82.178684,15.494665

In [128]:
summary_file = RAW_PATH / f"summary_{LA_CODE}.csv"
summary.to_csv(summary_file, index=False)
print("Saved:", summary_file)

Saved: C:\Users\swapn\OneDrive\Desktop\fuel_poverty_risk_england\data\raw\summary_E06000047.csv