In [3]:
import pandas as pd
from pathlib import Path

In [5]:
PROJECT_ROOT = Path(r"C:\Users\swapn\OneDrive\Desktop\fuel_poverty_risk_england")
RAW_PATH = PROJECT_ROOT / "data" / "raw"
LA_CODE = "E06000047"

In [7]:
elec_xls = pd.ExcelFile(RAW_PATH / "electricity_la_2005_2024.xlsx")
print(elec_xls.sheet_names)

['Cover sheet', '2005', '2006', '2007', '2008', '2009', '2010', '2012', '2011', '2013', '2014', '2015', '2016', '2017', '2018', '2019', '2020', '2021', '2022', '2023', '2024']

In [8]:
elec_test = pd.read_excel(RAW_PATH / "electricity_la_2005_2024.xlsx", sheet_name=0)
elec_test.head(15)

   Subnational electricity consumption, Great Britain, 2005 - 2024
0   This workbook presents Accredited Official Sta...
1   The electricity consumption years used in thes...
2                                            Contents
3   Following this Cover sheet this workbook conta...
4                                   Publication dates
5                  Publication date: 18 December 2025
6                          Next update: December 2026
7                                           Revisions
8   The statistics for the years 2015 onwards are ...
9   - Updates to the National Statistics Postcodes...
10  - Updates to the meter address information res...
11  - Additional information gathered about earlie...
12                                        Methodology
13  These figures are based on meter level electri...
14  Electricity data is divided between domestic a...

In [9]:
print(elec_xls.sheet_names)

['Cover sheet', '2005', '2006', '2007', '2008', '2009', '2010', '2012', '2011', '2013', '2014', '2015', '2016', '2017', '2018', '2019', '2020', '2021', '2022', '2023', '2024']

In [10]:
elec_2024 = pd.read_excel(RAW_PATH / "electricity_la_2005_2024.xlsx", sheet_name="2024")
elec_2024.head(15)

,"Subnational electricity consumption, Great Britain, 2024",Unnamed: 1,Unnamed: 2,Unnamed: 3,Unnamed: 4,Unnamed: 5,Unnamed: 6,Unnamed: 7,Unnamed: 8,Unnamed: 9,...,Unnamed: 14,Unnamed: 15,Unnamed: 16,Unnamed: 17,Unnamed: 18,Unnamed: 19,Unnamed: 20,Unnamed: 21,Unnamed: 22,Unnamed: 23
0,This table shows the electricity consumption a...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,Some consumption within given countries/region...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,Freeze panes are active on this sheet. To turn...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,Code,Country or region,Local authority,Number of meters\n(thousands):\nDomestic Standard,Number of meters\n(thousands):\nDomestic E7,Number of meters\n(thousands):\nAll Domestic,Number of meters\n(thousands):\nAll Non-Domestic,Number of meters\n(thousands):\nAll meters,Total consumption\n(GWh):\nDomestic Standard,Total consumption\n(GWh):\nDomestic E7,...,Mean consumption\n(kWh per meter):\nDomestic E7,Mean consumption\n(kWh per meter):\nAll Domestic,Mean consumption\n(kWh per meter):\nAll Non-Do...,Mean consumption\n(kWh per meter):\nAll meters,Median consumption\n(kWh per meter):\nDomestic...,Median consumption\n(kWh per meter):\nDomestic E7,Median consumption\n(kWh per meter):\nAll Dome...,Median consumption\n(kWh per meter):\nAll Non-...,Median consumption\n(kWh per meter):\nAll meters,Mean domestic\nconsumption\n(kWh per household)
4,K03000001,Great Britain (inc unallocated),All local authorities,25859.165,3485.197,29344.362,2466.418,31810.78,81247.039425,16256.515141,...,4664.446555,3322.735542,61524.089217,7835.321097,2398,3344.295,2471.1,6934,2543.7,3463.408415
5,K04000001,England and Wales (inc unallocated),All local authorities,23364.55,3177.15,26541.7,2249.288,28790.988,73964.380216,14739.107217,...,4639.097058,3342.042425,61747.065232,7904.91873,2415.3,3324.9,2487.6,6842.4,2560.1,3464.966838
6,E92000001,England,All local authorities,21989.611,3093.156,25082.767,2107.072,27189.839,69807.130251,14291.411663,...,4620.333298,3352.841491,60691.369605,7796.281083,2418,3310.5,2491.9,6895.4,2564.2,3473.850413
7,E12000001,North East,All local authorities,1206.275,52.278,1258.553,83.528,1342.081,3303.729257,249.196819,...,4766.762674,2823.024597,76358.930103,7399.728324,2188.3,3488.2,2212.3,7401.95,2269.2,2969.189382
8,E12000002,North West,All local authorities,3162.831,200.168,3362.999,240.731,3603.73,9632.137013,986.072027,...,4926.222106,3157.363127,68289.191848,7508.202469,2403.5,3737.05,2445.9,7874.4,2518.5,3285.77411
9,E12000003,Yorkshire and The Humber,All local authorities,2335.766,138.102,2473.868,186.582,2660.45,7034.884756,664.448986,...,4811.291554,3112.265385,68913.521216,7727.022255,2337.9,3533.3,2372.7,7585.9,2444.9,3232.637238
10,E12000004,East Midlands,All local authorities,1645.117,526.969,2172.086,169.856,2341.942,5136.601613,2085.371616,...,3957.294671,3324.902066,68324.872658,8039.209681,2408.972563,2775,2486.35,7948.85,2563.4,3424.260004
11,E12000005,West Midlands,All local authorities,2239.218,320.018,2559.236,206.837,2766.073,7155.738154,1437.211091,...,4491.032038,3357.622839,61450.542256,7701.602616,2486.3,3195.4,2547.1,7349.7,2621.5,3414.915813
12,E12000006,East,All local authorities,2188.219,610.947,2799.166,229.144,3028.31,7349.875175,2792.10751,...,4570.130486,3623.215874,58879.774656,7804.329731,2520.1,3195.2,2631.8,7410.75,2706.7,3796.318547
13,E12000007,London,All local authorities,3347.275,381.8,3729.075,390.545,4119.62,10382.302745,1702.402625,...,4458.88587,3240.671043,58164.898346,8447.554773,2287.9,3304.8,2357.4,5436.4,2423.012295,3302.319296
14,E13000001,Inner London,All local authorities,1476.252,123.399,1599.651,223.569,1823.22,4305.250547,576.721128,...,4673.62886,3051.897992,59807.753722,10011.48044,2071.8,3482.2,2130.9,4988.6,2209.8,3101.673258

In [11]:
elec_2024.columns.tolist()

['Subnational electricity consumption, Great Britain, 2024',
 'Unnamed: 1',
 'Unnamed: 2',
 'Unnamed: 3',
 'Unnamed: 4',
 'Unnamed: 5',
 'Unnamed: 6',
 'Unnamed: 7',
 'Unnamed: 8',
 'Unnamed: 9',
 'Unnamed: 10',
 'Unnamed: 11',
 'Unnamed: 12',
 'Unnamed: 13',
 'Unnamed: 14',
 'Unnamed: 15',
 'Unnamed: 16',
 'Unnamed: 17',
 'Unnamed: 18',
 'Unnamed: 19',
 'Unnamed: 20',
 'Unnamed: 21',
 'Unnamed: 22',
 'Unnamed: 23']

In [12]:
elec_2024.head(15)

,"Subnational electricity consumption, Great Britain, 2024",Unnamed: 1,Unnamed: 2,Unnamed: 3,Unnamed: 4,Unnamed: 5,Unnamed: 6,Unnamed: 7,Unnamed: 8,Unnamed: 9,...,Unnamed: 14,Unnamed: 15,Unnamed: 16,Unnamed: 17,Unnamed: 18,Unnamed: 19,Unnamed: 20,Unnamed: 21,Unnamed: 22,Unnamed: 23
0,This table shows the electricity consumption a...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,Some consumption within given countries/region...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,Freeze panes are active on this sheet. To turn...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,Code,Country or region,Local authority,Number of meters\n(thousands):\nDomestic Standard,Number of meters\n(thousands):\nDomestic E7,Number of meters\n(thousands):\nAll Domestic,Number of meters\n(thousands):\nAll Non-Domestic,Number of meters\n(thousands):\nAll meters,Total consumption\n(GWh):\nDomestic Standard,Total consumption\n(GWh):\nDomestic E7,...,Mean consumption\n(kWh per meter):\nDomestic E7,Mean consumption\n(kWh per meter):\nAll Domestic,Mean consumption\n(kWh per meter):\nAll Non-Do...,Mean consumption\n(kWh per meter):\nAll meters,Median consumption\n(kWh per meter):\nDomestic...,Median consumption\n(kWh per meter):\nDomestic E7,Median consumption\n(kWh per meter):\nAll Dome...,Median consumption\n(kWh per meter):\nAll Non-...,Median consumption\n(kWh per meter):\nAll meters,Mean domestic\nconsumption\n(kWh per household)
4,K03000001,Great Britain (inc unallocated),All local authorities,25859.165,3485.197,29344.362,2466.418,31810.78,81247.039425,16256.515141,...,4664.446555,3322.735542,61524.089217,7835.321097,2398,3344.295,2471.1,6934,2543.7,3463.408415
5,K04000001,England and Wales (inc unallocated),All local authorities,23364.55,3177.15,26541.7,2249.288,28790.988,73964.380216,14739.107217,...,4639.097058,3342.042425,61747.065232,7904.91873,2415.3,3324.9,2487.6,6842.4,2560.1,3464.966838
6,E92000001,England,All local authorities,21989.611,3093.156,25082.767,2107.072,27189.839,69807.130251,14291.411663,...,4620.333298,3352.841491,60691.369605,7796.281083,2418,3310.5,2491.9,6895.4,2564.2,3473.850413
7,E12000001,North East,All local authorities,1206.275,52.278,1258.553,83.528,1342.081,3303.729257,249.196819,...,4766.762674,2823.024597,76358.930103,7399.728324,2188.3,3488.2,2212.3,7401.95,2269.2,2969.189382
8,E12000002,North West,All local authorities,3162.831,200.168,3362.999,240.731,3603.73,9632.137013,986.072027,...,4926.222106,3157.363127,68289.191848,7508.202469,2403.5,3737.05,2445.9,7874.4,2518.5,3285.77411
9,E12000003,Yorkshire and The Humber,All local authorities,2335.766,138.102,2473.868,186.582,2660.45,7034.884756,664.448986,...,4811.291554,3112.265385,68913.521216,7727.022255,2337.9,3533.3,2372.7,7585.9,2444.9,3232.637238
10,E12000004,East Midlands,All local authorities,1645.117,526.969,2172.086,169.856,2341.942,5136.601613,2085.371616,...,3957.294671,3324.902066,68324.872658,8039.209681,2408.972563,2775,2486.35,7948.85,2563.4,3424.260004
11,E12000005,West Midlands,All local authorities,2239.218,320.018,2559.236,206.837,2766.073,7155.738154,1437.211091,...,4491.032038,3357.622839,61450.542256,7701.602616,2486.3,3195.4,2547.1,7349.7,2621.5,3414.915813
12,E12000006,East,All local authorities,2188.219,610.947,2799.166,229.144,3028.31,7349.875175,2792.10751,...,4570.130486,3623.215874,58879.774656,7804.329731,2520.1,3195.2,2631.8,7410.75,2706.7,3796.318547
13,E12000007,London,All local authorities,3347.275,381.8,3729.075,390.545,4119.62,10382.302745,1702.402625,...,4458.88587,3240.671043,58164.898346,8447.554773,2287.9,3304.8,2357.4,5436.4,2423.012295,3302.319296
14,E13000001,Inner London,All local authorities,1476.252,123.399,1599.651,223.569,1823.22,4305.250547,576.721128,...,4673.62886,3051.897992,59807.753722,10011.48044,2071.8,3482.2,2130.9,4988.6,2209.8,3101.673258

In [13]:
electricity_la = pd.read_excel(
    RAW_PATH / "electricity_la_2005_2024.xlsx",
    sheet_name="2024",
    header=3
)

electricity_la.head()

,"Freeze panes are active on this sheet. To turn off freeze panes select the 'View' ribbon then 'Freeze Panes' then 'Unfreeze Panes' or use [Alt W, F].",Unnamed: 1,Unnamed: 2,Unnamed: 3,Unnamed: 4,Unnamed: 5,Unnamed: 6,Unnamed: 7,Unnamed: 8,Unnamed: 9,...,Unnamed: 14,Unnamed: 15,Unnamed: 16,Unnamed: 17,Unnamed: 18,Unnamed: 19,Unnamed: 20,Unnamed: 21,Unnamed: 22,Unnamed: 23
0,Code,Country or region,Local authority,Number of meters\n(thousands):\nDomestic Standard,Number of meters\n(thousands):\nDomestic E7,Number of meters\n(thousands):\nAll Domestic,Number of meters\n(thousands):\nAll Non-Domestic,Number of meters\n(thousands):\nAll meters,Total consumption\n(GWh):\nDomestic Standard,Total consumption\n(GWh):\nDomestic E7,...,Mean consumption\n(kWh per meter):\nDomestic E7,Mean consumption\n(kWh per meter):\nAll Domestic,Mean consumption\n(kWh per meter):\nAll Non-Do...,Mean consumption\n(kWh per meter):\nAll meters,Median consumption\n(kWh per meter):\nDomestic...,Median consumption\n(kWh per meter):\nDomestic E7,Median consumption\n(kWh per meter):\nAll Dome...,Median consumption\n(kWh per meter):\nAll Non-...,Median consumption\n(kWh per meter):\nAll meters,Mean domestic\nconsumption\n(kWh per household)
1,K03000001,Great Britain (inc unallocated),All local authorities,25859.165,3485.197,29344.362,2466.418,31810.78,81247.039425,16256.515141,...,4664.446555,3322.735542,61524.089217,7835.321097,2398,3344.295,2471.1,6934,2543.7,3463.408415
2,K04000001,England and Wales (inc unallocated),All local authorities,23364.55,3177.15,26541.7,2249.288,28790.988,73964.380216,14739.107217,...,4639.097058,3342.042425,61747.065232,7904.91873,2415.3,3324.9,2487.6,6842.4,2560.1,3464.966838
3,E92000001,England,All local authorities,21989.611,3093.156,25082.767,2107.072,27189.839,69807.130251,14291.411663,...,4620.333298,3352.841491,60691.369605,7796.281083,2418,3310.5,2491.9,6895.4,2564.2,3473.850413
4,E12000001,North East,All local authorities,1206.275,52.278,1258.553,83.528,1342.081,3303.729257,249.196819,...,4766.762674,2823.024597,76358.930103,7399.728324,2188.3,3488.2,2212.3,7401.95,2269.2,2969.189382

In [14]:
electricity_la.columns.tolist()

["Freeze panes are active on this sheet. To turn off freeze panes select the 'View' ribbon then 'Freeze Panes' then 'Unfreeze Panes' or use [Alt W, F].",
 'Unnamed: 1',
 'Unnamed: 2',
 'Unnamed: 3',
 'Unnamed: 4',
 'Unnamed: 5',
 'Unnamed: 6',
 'Unnamed: 7',
 'Unnamed: 8',
 'Unnamed: 9',
 'Unnamed: 10',
 'Unnamed: 11',
 'Unnamed: 12',
 'Unnamed: 13',
 'Unnamed: 14',
 'Unnamed: 15',
 'Unnamed: 16',
 'Unnamed: 17',
 'Unnamed: 18',
 'Unnamed: 19',
 'Unnamed: 20',
 'Unnamed: 21',
 'Unnamed: 22',
 'Unnamed: 23']

In [23]:
pd.read_excel(RAW_PATH / "electricity_la_2005_2024.xlsx", sheet_name="2024", header=None).head(8)

,0,1,2,3,4,5,6,7,8,9,...,14,15,16,17,18,19,20,21,22,23
0,"Subnational electricity consumption, Great Bri...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,This table shows the electricity consumption a...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,Some consumption within given countries/region...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,Freeze panes are active on this sheet. To turn...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,Code,Country or region,Local authority,Number of meters\n(thousands):\nDomestic Standard,Number of meters\n(thousands):\nDomestic E7,Number of meters\n(thousands):\nAll Domestic,Number of meters\n(thousands):\nAll Non-Domestic,Number of meters\n(thousands):\nAll meters,Total consumption\n(GWh):\nDomestic Standard,Total consumption\n(GWh):\nDomestic E7,...,Mean consumption\n(kWh per meter):\nDomestic E7,Mean consumption\n(kWh per meter):\nAll Domestic,Mean consumption\n(kWh per meter):\nAll Non-Do...,Mean consumption\n(kWh per meter):\nAll meters,Median consumption\n(kWh per meter):\nDomestic...,Median consumption\n(kWh per meter):\nDomestic E7,Median consumption\n(kWh per meter):\nAll Dome...,Median consumption\n(kWh per meter):\nAll Non-...,Median consumption\n(kWh per meter):\nAll meters,Mean domestic\nconsumption\n(kWh per household)
5,K03000001,Great Britain (inc unallocated),All local authorities,25859.165,3485.197,29344.362,2466.418,31810.78,81247.039425,16256.515141,...,4664.446555,3322.735542,61524.089217,7835.321097,2398,3344.295,2471.1,6934,2543.7,3463.408415
6,K04000001,England and Wales (inc unallocated),All local authorities,23364.55,3177.15,26541.7,2249.288,28790.988,73964.380216,14739.107217,...,4639.097058,3342.042425,61747.065232,7904.91873,2415.3,3324.9,2487.6,6842.4,2560.1,3464.966838
7,E92000001,England,All local authorities,21989.611,3093.156,25082.767,2107.072,27189.839,69807.130251,14291.411663,...,4620.333298,3352.841491,60691.369605,7796.281083,2418,3310.5,2491.9,6895.4,2564.2,3473.850413

In [25]:
electricity_la = pd.read_excel(
    RAW_PATH / "electricity_la_2005_2024.xlsx",
    sheet_name="2024",
    header=4
)

electricity_la.head()

,Code,Country or region,Local authority,Number of meters\n(thousands):\nDomestic Standard,Number of meters\n(thousands):\nDomestic E7,Number of meters\n(thousands):\nAll Domestic,Number of meters\n(thousands):\nAll Non-Domestic,Number of meters\n(thousands):\nAll meters,Total consumption\n(GWh):\nDomestic Standard,Total consumption\n(GWh):\nDomestic E7,...,Mean consumption\n(kWh per meter):\nDomestic E7,Mean consumption\n(kWh per meter):\nAll Domestic,Mean consumption\n(kWh per meter):\nAll Non-Domestic,Mean consumption\n(kWh per meter):\nAll meters,Median consumption\n(kWh per meter):\nDomestic Standard,Median consumption\n(kWh per meter):\nDomestic E7,Median consumption\n(kWh per meter):\nAll Domestic,Median consumption\n(kWh per meter):\nAll Non-Domestic,Median consumption\n(kWh per meter):\nAll meters,Mean domestic\nconsumption\n(kWh per household)
0,K03000001,Great Britain (inc unallocated),All local authorities,25859.165,3485.197,29344.362,2466.418,31810.780,81247.039425,16256.515141,...,4664.446555,3322.735542,61524.089217,7835.321097,2398.0,3344.295,2471.1,6934.00,2543.7,3463.408415
1,K04000001,England and Wales (inc unallocated),All local authorities,23364.550,3177.150,26541.700,2249.288,28790.988,73964.380216,14739.107217,...,4639.097058,3342.042425,61747.065232,7904.918730,2415.3,3324.900,2487.6,6842.40,2560.1,3464.966838
2,E92000001,England,All local authorities,21989.611,3093.156,25082.767,2107.072,27189.839,69807.130251,14291.411663,...,4620.333298,3352.841491,60691.369605,7796.281083,2418.0,3310.500,2491.9,6895.40,2564.2,3473.850413
3,E12000001,North East,All local authorities,1206.275,52.278,1258.553,83.528,1342.081,3303.729257,249.196819,...,4766.762674,2823.024597,76358.930103,7399.728324,2188.3,3488.200,2212.3,7401.95,2269.2,2969.189382
4,E12000002,North West,All local authorities,3162.831,200.168,3362.999,240.731,3603.730,9632.137013,986.072027,...,4926.222106,3157.363127,68289.191848,7508.202469,2403.5,3737.050,2445.9,7874.40,2518.5,3285.774110

In [27]:
electricity_cd = electricity_la[electricity_la["Code"] == LA_CODE].copy()
electricity_cd

,Code,Country or region,Local authority,Number of meters\n(thousands):\nDomestic Standard,Number of meters\n(thousands):\nDomestic E7,Number of meters\n(thousands):\nAll Domestic,Number of meters\n(thousands):\nAll Non-Domestic,Number of meters\n(thousands):\nAll meters,Total consumption\n(GWh):\nDomestic Standard,Total consumption\n(GWh):\nDomestic E7,...,Mean consumption\n(kWh per meter):\nDomestic E7,Mean consumption\n(kWh per meter):\nAll Domestic,Mean consumption\n(kWh per meter):\nAll Non-Domestic,Mean consumption\n(kWh per meter):\nAll meters,Median consumption\n(kWh per meter):\nDomestic Standard,Median consumption\n(kWh per meter):\nDomestic E7,Median consumption\n(kWh per meter):\nAll Domestic,Median consumption\n(kWh per meter):\nAll Non-Domestic,Median consumption\n(kWh per meter):\nAll meters,Mean domestic\nconsumption\n(kWh per household)
24,E06000047,North East,County Durham,241.822,6.735,248.557,15.99,264.547,665.210853,34.216167,...,5080.351441,2813.950202,65130.069871,6580.520049,2186.4,3640.2,2201.7,7042.813,2256.7,2909.115571

In [29]:
postcode_join = pd.read_csv(RAW_PATH / f"postcode_epc_fuelpoverty_{LA_CODE}.csv")
postcode_join.head()

,postcode,properties,share_low_rating,share_low_efficiency,avg_current_efficiency,avg_potential_efficiency,avg_improvement_gap,risk_score,risk_band,la_fuel_poverty_pct
0,DH1 1AF,35,0.114286,0.114286,64.600000,79.371429,14.771429,0.141080,High,11.4
1,DH1 1AH,31,0.129032,0.129032,63.000000,78.709677,15.709677,0.156031,High,11.4
2,DH1 1AL,31,0.096774,0.096774,63.516129,79.838710,16.322581,0.132285,High,11.4
3,DH1 1AQ,22,0.181818,0.181818,61.318182,79.636364,18.318182,0.207028,Very High,11.4
4,DH1 1AS,36,0.166667,0.166667,62.222222,82.666667,20.444444,0.202054,High,11.4

In [31]:
postcode_join.columns.tolist(), electricity_cd.columns.tolist()

(['postcode',
  'properties',
  'share_low_rating',
  'share_low_efficiency',
  'avg_current_efficiency',
  'avg_potential_efficiency',
  'avg_improvement_gap',
  'risk_score',
  'risk_band',
  'la_fuel_poverty_pct'],
 ['Code',
  'Country or region',
  'Local authority',
  'Number of meters\n(thousands):\nDomestic Standard',
  'Number of meters\n(thousands):\nDomestic E7',
  'Number of meters\n(thousands):\nAll Domestic',
  'Number of meters\n(thousands):\nAll Non-Domestic',
  'Number of meters\n(thousands):\nAll meters',
  'Total consumption\n(GWh):\nDomestic Standard',
  'Total consumption\n(GWh):\nDomestic E7',
  'Total consumption\n(GWh):\nAll Domestic',
  'Total consumption\n(GWh):\nAll Non-Domestic',
  'Total consumption\n(GWh):\nAll meters',
  'Mean consumption\n(kWh per meter):\nDomestic Standard',
  'Mean consumption\n(kWh per meter):\nDomestic E7',
  'Mean consumption\n(kWh per meter):\nAll Domestic',
  'Mean consumption\n(kWh per meter):\nAll Non-Domestic',
  'Mean consumption\n(kWh per meter):\nAll meters',
  'Median consumption\n(kWh per meter):\nDomestic Standard',
  'Median consumption\n(kWh per meter):\nDomestic E7',
  'Median consumption\n(kWh per meter):\nAll Domestic',
  'Median consumption\n(kWh per meter):\nAll Non-Domestic',
  'Median consumption\n(kWh per meter):\nAll meters',
  'Mean domestic\nconsumption\n(kWh per household)'])

In [33]:
postcode_join.columns.tolist(), electricity_cd.columns.tolist()

(['postcode',
  'properties',
  'share_low_rating',
  'share_low_efficiency',
  'avg_current_efficiency',
  'avg_potential_efficiency',
  'avg_improvement_gap',
  'risk_score',
  'risk_band',
  'la_fuel_poverty_pct'],
 ['Code',
  'Country or region',
  'Local authority',
  'Number of meters\n(thousands):\nDomestic Standard',
  'Number of meters\n(thousands):\nDomestic E7',
  'Number of meters\n(thousands):\nAll Domestic',
  'Number of meters\n(thousands):\nAll Non-Domestic',
  'Number of meters\n(thousands):\nAll meters',
  'Total consumption\n(GWh):\nDomestic Standard',
  'Total consumption\n(GWh):\nDomestic E7',
  'Total consumption\n(GWh):\nAll Domestic',
  'Total consumption\n(GWh):\nAll Non-Domestic',
  'Total consumption\n(GWh):\nAll meters',
  'Mean consumption\n(kWh per meter):\nDomestic Standard',
  'Mean consumption\n(kWh per meter):\nDomestic E7',
  'Mean consumption\n(kWh per meter):\nAll Domestic',
  'Mean consumption\n(kWh per meter):\nAll Non-Domestic',
  'Mean consumption\n(kWh per meter):\nAll meters',
  'Median consumption\n(kWh per meter):\nDomestic Standard',
  'Median consumption\n(kWh per meter):\nDomestic E7',
  'Median consumption\n(kWh per meter):\nAll Domestic',
  'Median consumption\n(kWh per meter):\nAll Non-Domestic',
  'Median consumption\n(kWh per meter):\nAll meters',
  'Mean domestic\nconsumption\n(kWh per household)'])

In [35]:
postcode_join["la_elec_total_gwh"] = float(electricity_cd["Total consumption\n(GWh):\nAll Domestic"].iloc[0])
postcode_join["la_elec_mean_kwh_per_meter"] = float(electricity_cd["Mean consumption\n(kWh per meter):\nAll Domestic"].iloc[0])
postcode_join["la_mean_domestic_kwh_per_household"] = float(electricity_cd["Mean domestic\nconsumption\n(kWh per household)"].iloc[0])

postcode_join.head()

,postcode,properties,share_low_rating,share_low_efficiency,avg_current_efficiency,avg_potential_efficiency,avg_improvement_gap,risk_score,risk_band,la_fuel_poverty_pct,la_elec_total_gwh,la_elec_mean_kwh_per_meter,la_mean_domestic_kwh_per_household
0,DH1 1AF,35,0.114286,0.114286,64.600000,79.371429,14.771429,0.141080,High,11.4,699.42702,2813.950202,2909.115571
1,DH1 1AH,31,0.129032,0.129032,63.000000,78.709677,15.709677,0.156031,High,11.4,699.42702,2813.950202,2909.115571
2,DH1 1AL,31,0.096774,0.096774,63.516129,79.838710,16.322581,0.132285,High,11.4,699.42702,2813.950202,2909.115571
3,DH1 1AQ,22,0.181818,0.181818,61.318182,79.636364,18.318182,0.207028,Very High,11.4,699.42702,2813.950202,2909.115571
4,DH1 1AS,36,0.166667,0.166667,62.222222,82.666667,20.444444,0.202054,High,11.4,699.42702,2813.950202,2909.115571

In [37]:
gas_xls = pd.ExcelFile(RAW_PATH / "gas_la_2005_2024.xlsx")
print(gas_xls.sheet_names)

['Cover sheet', 'Notes', '2005', '2006', '2007', '2008', '2009', '2010', '2011', '2012', '2013', '2014', '2015', '2016', '2017', '2018', '2019', '2020', '2021', '2022', '2023', '2024']

In [39]:
gas_2024 = pd.read_excel(RAW_PATH / "gas_la_2005_2024.xlsx", sheet_name="2024", header=4)
gas_2024.head()

,"Freeze panes are active on this sheet. To turn off freeze panes select the 'View' ribbon then 'Freeze Panes' then 'Unfreeze Panes' or use [Alt W, F].",Unnamed: 1,Unnamed: 2,Unnamed: 3,Unnamed: 4,Unnamed: 5,Unnamed: 6,Unnamed: 7,Unnamed: 8,Unnamed: 9,Unnamed: 10,Unnamed: 11,Unnamed: 12,Unnamed: 13,Unnamed: 14,Unnamed: 15,Unnamed: 16
0,Code,Country or region,Local authority,Notes,Number of meters\n(thousands):\nDomestic\n,Number of meters\n(thousands):\nNon-Domestic,Number of meters\n(thousands):\nAll meters,Total consumption\n(GWh):\nDomestic\n,Total consumption\n(GWh):\nNon-Domestic,Total consumption\n(GWh):\nAll meters,Mean consumption\n(kWh per meter):\nDomestic\n,Mean consumption\n(kWh per meter):\nNon-Domestic,Mean consumption\n(kWh per meter):\nAll meters,Median consumption\n(kWh per meter):\nDomestic\n,Median consumption\n(kWh per meter):\nNon-Dome...,Median consumption\n(kWh per meter):\nAll meters,Number of \nnon-consuming meters \n(thousands)
1,K03000001,Great Britain (inc unallocated),All local authorities,NaN,24702.708,233.229,24935.937,280605.464567,157399.279037,438004.743604,11359.29974,674870.102075,17565.200923,9859.286639,148289.344293,9929.021214,376.875
2,K04000001,England and Wales (inc unallocated),All local authorities,NaN,22525.093,212.403,22737.496,255520.906282,140762.145666,396283.051948,11343.833576,662712.606066,17428.614477,9850.521734,147039.25017,9919.738597,342.547
3,E92000001,England,All local authorities,NaN,21330.911,202.502,21533.413,242971.927381,130134.005481,373105.932862,11390.602463,642630.717135,17326.836803,9881.399368,146716.119079,9950.831533,324.17
4,E12000001,North East,All local authorities,NaN,1170.949,10.045,1180.994,13471.171946,7193.333057,20664.505004,11504.490756,716110.807106,17497.552912,10325.228457,154684.089402,10381.327782,17.18

In [41]:
gas_2024 = pd.read_excel(RAW_PATH / "gas_la_2005_2024.xlsx", sheet_name="2024", header=5)
gas_2024.head()

,Code,Country or region,Local authority,Notes,Number of meters\n(thousands):\nDomestic\n,Number of meters\n(thousands):\nNon-Domestic,Number of meters\n(thousands):\nAll meters,Total consumption\n(GWh):\nDomestic\n,Total consumption\n(GWh):\nNon-Domestic,Total consumption\n(GWh):\nAll meters,Mean consumption\n(kWh per meter):\nDomestic\n,Mean consumption\n(kWh per meter):\nNon-Domestic,Mean consumption\n(kWh per meter):\nAll meters,Median consumption\n(kWh per meter):\nDomestic\n,Median consumption\n(kWh per meter):\nNon-Domestic,Median consumption\n(kWh per meter):\nAll meters,Number of \nnon-consuming meters \n(thousands)
0,K03000001,Great Britain (inc unallocated),All local authorities,NaN,24702.708,233.229,24935.937,280605.464567,157399.279037,438004.743604,11359.299740,674870.102075,17565.200923,9859.286639,148289.344293,9929.021214,376.875
1,K04000001,England and Wales (inc unallocated),All local authorities,NaN,22525.093,212.403,22737.496,255520.906282,140762.145666,396283.051948,11343.833576,662712.606066,17428.614477,9850.521734,147039.250170,9919.738597,342.547
2,E92000001,England,All local authorities,NaN,21330.911,202.502,21533.413,242971.927381,130134.005481,373105.932862,11390.602463,642630.717135,17326.836803,9881.399368,146716.119079,9950.831533,324.170
3,E12000001,North East,All local authorities,NaN,1170.949,10.045,1180.994,13471.171946,7193.333057,20664.505004,11504.490756,716110.807106,17497.552912,10325.228457,154684.089402,10381.327782,17.180
4,E12000002,North West,All local authorities,NaN,3040.306,26.836,3067.142,33841.192833,22208.675855,56049.868688,11130.850919,827570.273325,18274.298578,9776.600928,149560.395300,9836.646504,52.531

In [43]:
gas_cd = gas_2024[gas_2024["Code"] == LA_CODE].copy()
gas_cd

,Code,Country or region,Local authority,Notes,Number of meters\n(thousands):\nDomestic\n,Number of meters\n(thousands):\nNon-Domestic,Number of meters\n(thousands):\nAll meters,Total consumption\n(GWh):\nDomestic\n,Total consumption\n(GWh):\nNon-Domestic,Total consumption\n(GWh):\nAll meters,Mean consumption\n(kWh per meter):\nDomestic\n,Mean consumption\n(kWh per meter):\nNon-Domestic,Mean consumption\n(kWh per meter):\nAll meters,Median consumption\n(kWh per meter):\nDomestic\n,Median consumption\n(kWh per meter):\nNon-Domestic,Median consumption\n(kWh per meter):\nAll meters,Number of \nnon-consuming meters \n(thousands)
24,E06000047,North East,County Durham,NaN,234.967,1.839,236.806,2745.079646,1028.626809,3773.706455,11682.830549,559340.298782,15935.856587,10636.235243,150883.735453,10692.334569,3.284

In [47]:
postcode_join["la_gas_total_gwh"] = float(gas_cd["Total consumption\n(GWh):\nDomestic"].iloc[0])
postcode_join["la_gas_mean_kwh_per_meter"] = float(gas_cd["Mean consumption\n(kWh per meter):\nDomestic"].iloc[0])

postcode_join.head()

KeyError: 'Total consumption\n(GWh):\nDomestic'

In [49]:
gas_cd.columns.tolist()

['Code',
 'Country or region',
 'Local authority',
 'Notes',
 'Number of meters\n(thousands):\nDomestic\n',
 'Number of meters\n(thousands):\nNon-Domestic',
 'Number of meters\n(thousands):\nAll meters',
 'Total consumption\n(GWh):\nDomestic\n',
 'Total consumption\n(GWh):\nNon-Domestic',
 'Total consumption\n(GWh):\nAll meters',
 'Mean consumption\n(kWh per meter):\nDomestic\n',
 'Mean consumption\n(kWh per meter):\nNon-Domestic',
 'Mean consumption\n(kWh per meter):\nAll meters',
 'Median consumption\n(kWh per meter):\nDomestic\n',
 'Median consumption\n(kWh per meter):\nNon-Domestic',
 'Median consumption\n(kWh per meter):\nAll meters',
 'Number of \nnon-consuming meters \n(thousands)']

In [51]:
postcode_join["la_gas_total_gwh"] = float(gas_cd["Total consumption\n(GWh):\nDomestic\n"].iloc[0])
postcode_join["la_gas_mean_kwh_per_meter"] = float(gas_cd["Mean consumption\n(kWh per meter):\nDomestic\n"].iloc[0])

postcode_join.head()

,postcode,properties,share_low_rating,share_low_efficiency,avg_current_efficiency,avg_potential_efficiency,avg_improvement_gap,risk_score,risk_band,la_fuel_poverty_pct,la_elec_total_gwh,la_elec_mean_kwh_per_meter,la_mean_domestic_kwh_per_household,la_gas_total_gwh,la_gas_mean_kwh_per_meter
0,DH1 1AF,35,0.114286,0.114286,64.600000,79.371429,14.771429,0.141080,High,11.4,699.42702,2813.950202,2909.115571,2745.079646,11682.830549
1,DH1 1AH,31,0.129032,0.129032,63.000000,78.709677,15.709677,0.156031,High,11.4,699.42702,2813.950202,2909.115571,2745.079646,11682.830549
2,DH1 1AL,31,0.096774,0.096774,63.516129,79.838710,16.322581,0.132285,High,11.4,699.42702,2813.950202,2909.115571,2745.079646,11682.830549
3,DH1 1AQ,22,0.181818,0.181818,61.318182,79.636364,18.318182,0.207028,Very High,11.4,699.42702,2813.950202,2909.115571,2745.079646,11682.830549
4,DH1 1AS,36,0.166667,0.166667,62.222222,82.666667,20.444444,0.202054,High,11.4,699.42702,2813.950202,2909.115571,2745.079646,11682.830549

In [53]:
iod_xls = pd.ExcelFile(RAW_PATH / "iod2025_la_summary_v2.xlsx")
print(iod_xls.sheet_names)

['Notes', 'IMD', 'Income', 'Employment', 'Education', 'Health', 'Crime', 'Barriers', 'Living', 'IDACI', 'IDAOPI']

In [55]:
imd_test = pd.read_excel(RAW_PATH / "iod2025_la_summary_v2.xlsx", sheet_name="IMD")
imd_test.head(15)

,Local Authority District code (2024),Local Authority District name (2024),IMD - Average rank,IMD - Rank of average rank,IMD - Average score,IMD - Rank of average score,IMD - Proportion of LSOAs in most deprived 10% nationally,IMD - Rank of proportion of LSOAs in most deprived 10% nationally,IMD25 - Extent,IMD25 - Rank of extent,IMD25 - Local concentration,IMD25 - Rank of local concentration
0,E06000001,Hartlepool,23075.98,30,37.580,6,0.4211,3,0.5259,8,33623.27,3
1,E06000002,Middlesbrough,23840.54,21,40.037,2,0.5000,1,0.5657,3,33672.10,2
2,E06000003,Redcar and Cleveland,20592.69,62,30.336,37,0.2500,25,0.3665,44,33529.27,7
3,E06000004,Stockton-on-Tees,17658.71,119,25.830,69,0.1935,41,0.3182,59,33332.64,17
4,E06000005,Darlington,18611.35,103,25.713,72,0.1970,40,0.2814,69,33117.99,30
5,E06000006,Halton,20886.57,55,31.117,31,0.3125,16,0.4290,27,33327.38,18
6,E06000007,Warrington,13072.02,199,16.835,174,0.0606,114,0.1561,121,30722.59,114
7,E06000008,Blackburn with Darwen,24567.65,11,36.899,10,0.3736,9,0.5702,2,33262.48,24
8,E06000009,Blackpool,26536.86,1,43.467,1,0.4043,6,0.5217,9,33748.14,1
9,E06000010,"Kingston upon Hull, City of",24324.73,14,37.206,8,0.4167,4,0.5200,11,33340.11,16
10,E06000011,East Riding of Yorkshire,12648.72,203,15.755,189,0.0610,113,0.0982,155,30438.49,120
11,E06000012,North East Lincolnshire,19754.27,81,30.213,39,0.2710,21,0.3698,38,33609.96,4
12,E06000013,North Lincolnshire,18590.12,104,23.473,99,0.1165,77,0.2107,98,32214.66,63
13,E06000014,York,9512.50,261,11.814,251,0.0000,193,0.0682,179,27798.04,176
14,E06000015,Derby,19898.13,79,28.155,52,0.1842,46,0.3611,45,33110.37,32

In [57]:
imd_cd = imd_test[imd_test["Local Authority District code (2024)"] == LA_CODE].copy()
imd_cd

,Local Authority District code (2024),Local Authority District name (2024),IMD - Average rank,IMD - Rank of average rank,IMD - Average score,IMD - Rank of average score,IMD - Proportion of LSOAs in most deprived 10% nationally,IMD - Rank of proportion of LSOAs in most deprived 10% nationally,IMD25 - Extent,IMD25 - Rank of extent,IMD25 - Local concentration,IMD25 - Rank of local concentration
44,E06000047,County Durham,21488.54,47,28.808,49,0.1697,53,0.3602,46,32636.06,49

In [61]:
imd_cd.columns.tolist()

['Local Authority District code (2024)',
 'Local Authority District name (2024)',
 'IMD - Average rank ',
 'IMD - Rank of average rank ',
 'IMD - Average score ',
 'IMD - Rank of average score ',
 'IMD - Proportion of LSOAs in most deprived 10% nationally ',
 'IMD - Rank of proportion of LSOAs in most deprived 10% nationally ',
 'IMD25 - Extent ',
 'IMD25 - Rank of extent ',
 'IMD25 - Local concentration ',
 'IMD25 - Rank of local concentration ']

In [63]:
postcode_join["la_imd_average_rank"] = float(imd_cd["IMD - Average rank "].iloc[0])
postcode_join["la_imd_average_score"] = float(imd_cd["IMD - Average score "].iloc[0])
postcode_join["la_imd_most_deprived_10pct_share"] = float(
    imd_cd["IMD - Proportion of LSOAs in most deprived 10% nationally "].iloc[0]
)

postcode_join.head()

,postcode,properties,share_low_rating,share_low_efficiency,avg_current_efficiency,avg_potential_efficiency,avg_improvement_gap,risk_score,risk_band,la_fuel_poverty_pct,la_elec_total_gwh,la_elec_mean_kwh_per_meter,la_mean_domestic_kwh_per_household,la_gas_total_gwh,la_gas_mean_kwh_per_meter,la_imd_average_rank,la_imd_average_score,la_imd_most_deprived_10pct_share
0,DH1 1AF,35,0.114286,0.114286,64.600000,79.371429,14.771429,0.141080,High,11.4,699.42702,2813.950202,2909.115571,2745.079646,11682.830549,21488.54,28.808,0.1697
1,DH1 1AH,31,0.129032,0.129032,63.000000,78.709677,15.709677,0.156031,High,11.4,699.42702,2813.950202,2909.115571,2745.079646,11682.830549,21488.54,28.808,0.1697
2,DH1 1AL,31,0.096774,0.096774,63.516129,79.838710,16.322581,0.132285,High,11.4,699.42702,2813.950202,2909.115571,2745.079646,11682.830549,21488.54,28.808,0.1697
3,DH1 1AQ,22,0.181818,0.181818,61.318182,79.636364,18.318182,0.207028,Very High,11.4,699.42702,2813.950202,2909.115571,2745.079646,11682.830549,21488.54,28.808,0.1697
4,DH1 1AS,36,0.166667,0.166667,62.222222,82.666667,20.444444,0.202054,High,11.4,699.42702,2813.950202,2909.115571,2745.079646,11682.830549,21488.54,28.808,0.1697

In [65]:
final_join_file = RAW_PATH / f"postcode_master_{LA_CODE}.csv"
postcode_join.to_csv(final_join_file, index=False)
print("Saved:", final_join_file)

Saved: C:\Users\swapn\OneDrive\Desktop\fuel_poverty_risk_england\data\raw\postcode_master_E06000047.csv